### ISSUE TITLE
Limit delta-v from solid fuel boosters

### ISSUE THREAD

**Issue by popiel** [aandergr/kspalculator#15]
When designing rockets for getting to Kerbin orbit, it's frequently necessary to have a coasting period mid-flight.  If the solid fuel boosters are still burning when that coasting is supposed to begin, then there's big problems.  This tends to happen a lot for payloads under 5 tons when the calculator tries to use the Kickback boosters.

It would be nice to be able to indicate that the solid fuel boosters must be done burning by the end of a particular flight phase.

**Comment by aandergr** [comment]
Implemented by 9bc1299 in pull request #16 - Thank you!
